# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-03 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('businessplan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessplan',
            options={'ordering': ['-updated', '-timestamp']},
        ),
        migrations.AddField(
            model_name='businessplan',
            name='plan',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='businessplan',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessplan',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
