# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-03 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessplan', '0002_auto_20180203_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessplan',
            name='model',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
    ]
