# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-15 16:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('organisation', models.IntegerField(blank=True, null=True)),
                ('leadership', models.IntegerField(blank=True, null=True)),
                ('staff', models.IntegerField(blank=True, null=True)),
                ('hr', models.IntegerField(blank=True, null=True)),
                ('facilities', models.IntegerField(blank=True, null=True)),
                ('finance', models.IntegerField(blank=True, null=True)),
                ('manproc', models.IntegerField(blank=True, null=True)),
                ('marketing', models.IntegerField(blank=True, null=True)),
                ('environ', models.IntegerField(blank=True, null=True)),
                ('IT', models.IntegerField(blank=True, null=True)),
                ('legal', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated', '-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticsQuestionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('organisation', models.IntegerField(choices=[(1, 'Equity'), (2, 'Trade'), (3, 'Debt')], default=0)),
                ('leadership', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated', '-timestamp'],
            },
        ),
    ]
