# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-18 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='investor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='sme',
            field=models.BooleanField(default=False),
        ),
    ]
