# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-24 18:45
from __future__ import unicode_literals

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20171224_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='smeprofile',
            name='country',
            field=django_countries.fields.CountryField(default='GB', max_length=2),
            preserve_default=False,
        ),
    ]
