# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-24 19:21
from __future__ import unicode_literals

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20171224_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='smeprofile',
            name='currency',
            field=djmoney.models.fields.CurrencyField(default='GBP', max_length=3),
        ),
    ]
