# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-25 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20171224_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='smeprofile',
            name='lkin_urls',
            field=models.URLField(blank=True, null=True),
        ),
    ]
