# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-25 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_smeprofile_lkin_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='smeprofile',
            name='sector',
            field=models.CharField(choices=[('Agriculture', (('fruit', 'Fruit'), ('coffee', 'Coffee'))), ('Hospitality', (('bar', 'Bar'), ('restaurant', 'Restaurant')))], default='Coffee', max_length=50),
            preserve_default=False,
        ),
    ]
