# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-25 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20171225_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='smeprofile',
            name='avatar',
            field=models.ImageField(default='static/logos/logo.png', upload_to=''),
        ),
    ]
