# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-03 18:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_auto_20180103_1642'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investorprofile',
            options={'ordering': ['-updated', '-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='smeprofile',
            options={'ordering': ['-updated', '-timestamp']},
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='smeprofile',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smeprofile',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
