# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-05 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_auto_20180103_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='investorprofile',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smeprofile',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investorprofile',
            name='deal',
            field=models.CharField(choices=[('Equity', 'Equity'), ('Trade', 'Trade'), ('Debt', 'Debt')], max_length=1),
        ),
    ]
