# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-10 16:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dataroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='None', max_length=1500)),
                ('file', models.FileField(upload_to='compliance/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='compliance',
            name='user',
        ),
        migrations.DeleteModel(
            name='Compliance',
        ),
    ]
