# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-14 19:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dataroom', '0003_companymodel_competitionmodel_environmentalmodel_facilitiesmodel_financemodel_governancemodel_legalm'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccordionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='file',
            field=models.FileField(upload_to='company/'),
        ),
        migrations.AlterField(
            model_name='competitionmodel',
            name='file',
            field=models.FileField(upload_to='competition/'),
        ),
        migrations.AlterField(
            model_name='environmentalmodel',
            name='file',
            field=models.FileField(upload_to='environmental/'),
        ),
        migrations.AlterField(
            model_name='facilitiesmodel',
            name='file',
            field=models.FileField(upload_to='facilities/'),
        ),
        migrations.AlterField(
            model_name='financemodel',
            name='file',
            field=models.FileField(upload_to='finance/'),
        ),
        migrations.AlterField(
            model_name='governancemodel',
            name='file',
            field=models.FileField(upload_to='governance/'),
        ),
        migrations.AlterField(
            model_name='legalmodel',
            name='file',
            field=models.FileField(upload_to='legal/'),
        ),
        migrations.AlterField(
            model_name='marketingmodel',
            name='file',
            field=models.FileField(upload_to='marketing/'),
        ),
        migrations.AlterField(
            model_name='organisationmodel',
            name='file',
            field=models.FileField(upload_to='organisation/'),
        ),
        migrations.AlterField(
            model_name='processesmodel',
            name='file',
            field=models.FileField(upload_to='processes/'),
        ),
        migrations.AlterField(
            model_name='procurementmodel',
            name='file',
            field=models.FileField(upload_to='procurement/'),
        ),
        migrations.AlterField(
            model_name='staffmodel',
            name='file',
            field=models.FileField(upload_to='staff/'),
        ),
        migrations.AlterField(
            model_name='technologymodel',
            name='file',
            field=models.FileField(upload_to='technology/'),
        ),
        migrations.AddField(
            model_name='companymodel',
            name='accordion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dataroom.AccordionModel'),
        ),
        migrations.AddField(
            model_name='competitionmodel',
            name='accordion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dataroom.AccordionModel'),
        ),
        migrations.AddField(
            model_name='compliancemodel',
            name='accordion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dataroom.AccordionModel'),
        ),
        migrations.AddField(
            model_name='environmentalmodel',
            name='accordion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dataroom.AccordionModel'),
        ),
        migrations.AddField(
            model_name='facilitiesmodel',
            name='accordion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dataroom.AccordionModel'),
        ),
        migrations.AddField(
            model_name='financemodel',
            name='accordion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dataroom.AccordionModel'),
        ),
        migrations.AddField(
            model_name='governancemodel',
            name='accordion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dataroom.AccordionModel'),
        ),
        migrations.AddField(
            model_name='legalmodel',
            name='accordion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dataroom.AccordionModel'),
        ),
        migrations.AddField(
            model_name='marketingmodel',
            name='accordion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dataroom.AccordionModel'),
        ),
        migrations.AddField(
            model_name='organisationmodel',
            name='accordion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dataroom.AccordionModel'),
        ),
        migrations.AddField(
            model_name='processesmodel',
            name='accordion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dataroom.AccordionModel'),
        ),
        migrations.AddField(
            model_name='procurementmodel',
            name='accordion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dataroom.AccordionModel'),
        ),
        migrations.AddField(
            model_name='staffmodel',
            name='accordion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dataroom.AccordionModel'),
        ),
        migrations.AddField(
            model_name='technologymodel',
            name='accordion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dataroom.AccordionModel'),
        ),
    ]
