# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-14 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0004_auto_20180314_1910'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccordionModel',
            new_name='Accordion',
        ),
    ]
