# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-14 22:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dataroom', '0006_accordion_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccordionFileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='None', max_length=1500)),
                ('file', models.FileField(upload_to='compliance/')),
                ('sub_area', models.CharField(default='None', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('accordion', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dataroom.Accordion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='companymodel',
            name='accordion',
        ),
        migrations.RemoveField(
            model_name='companymodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='competitionmodel',
            name='accordion',
        ),
        migrations.RemoveField(
            model_name='competitionmodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='compliancemodel',
            name='accordion',
        ),
        migrations.RemoveField(
            model_name='compliancemodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='environmentalmodel',
            name='accordion',
        ),
        migrations.RemoveField(
            model_name='environmentalmodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='facilitiesmodel',
            name='accordion',
        ),
        migrations.RemoveField(
            model_name='facilitiesmodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='financemodel',
            name='accordion',
        ),
        migrations.RemoveField(
            model_name='financemodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='governancemodel',
            name='accordion',
        ),
        migrations.RemoveField(
            model_name='governancemodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='legalmodel',
            name='accordion',
        ),
        migrations.RemoveField(
            model_name='legalmodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='marketingmodel',
            name='accordion',
        ),
        migrations.RemoveField(
            model_name='marketingmodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='organisationmodel',
            name='accordion',
        ),
        migrations.RemoveField(
            model_name='organisationmodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='processesmodel',
            name='accordion',
        ),
        migrations.RemoveField(
            model_name='processesmodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='procurementmodel',
            name='accordion',
        ),
        migrations.RemoveField(
            model_name='procurementmodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='staffmodel',
            name='accordion',
        ),
        migrations.RemoveField(
            model_name='staffmodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='technologymodel',
            name='accordion',
        ),
        migrations.RemoveField(
            model_name='technologymodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='CompanyModel',
        ),
        migrations.DeleteModel(
            name='CompetitionModel',
        ),
        migrations.DeleteModel(
            name='ComplianceModel',
        ),
        migrations.DeleteModel(
            name='EnvironmentalModel',
        ),
        migrations.DeleteModel(
            name='FacilitiesModel',
        ),
        migrations.DeleteModel(
            name='FinanceModel',
        ),
        migrations.DeleteModel(
            name='GovernanceModel',
        ),
        migrations.DeleteModel(
            name='LegalModel',
        ),
        migrations.DeleteModel(
            name='MarketingModel',
        ),
        migrations.DeleteModel(
            name='OrganisationModel',
        ),
        migrations.DeleteModel(
            name='ProcessesModel',
        ),
        migrations.DeleteModel(
            name='ProcurementModel',
        ),
        migrations.DeleteModel(
            name='StaffModel',
        ),
        migrations.DeleteModel(
            name='TechnologyModel',
        ),
    ]
