# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-22 18:40
from __future__ import unicode_literals

import dataroom.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0007_auto_20180314_2237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accordion',
            options={'ordering': ['-updated', '-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='accordionfilemodel',
            options={'ordering': ['-updated', '-timestamp']},
        ),
        migrations.AlterField(
            model_name='accordionfilemodel',
            name='file',
            field=models.FileField(upload_to=dataroom.models.get_upload_path),
        ),
    ]
