# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-01 19:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0002_grossandnet_year'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GrossAndNet',
            new_name='GraphData',
        ),
    ]
