# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-13 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0005_exceltemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphdata',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
