# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-21 19:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0006_graphdata_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GraphData',
            new_name='GraphData_follower',
        ),
    ]
